# Generated by Django 4.2.2 on 2025-01-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Введите номер телефона",
                max_length=35,
                null=True,
                unique=True,
                verbose_name="Телефон",
            ),
        ),
    ]
