# Generated by Django 4.2.2 on 2025-01-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_diary_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="content",
            field=models.TextField(verbose_name="Содержание"),
        ),
    ]
